apiVersion: v1
kind: Service
metadata:
  name: my-express-service
spec:
  type: NodePort
  ports:
    - port: 80 # запрос сюда перенаправит на targetPort в selector Deployment
      targetPort: 3010
      nodePort: 30002
  selector:
    app: my-express-app
